### ISSUE TITLE
Failed to create NodeNetworkConfigurationPolicy resources in kube-nmstate

### ISSUE THREAD

**Issue by mardim91** [nmstate/kubernetes-nmstate#402] opened 2020-02-10 17:09 UTC
**What happened**:

Try to create NodeNetworkConfigurationPolicy resources in my kubernetes cluster through the kube-nmstate but all the endeavours are failing.

**What you expected to happen**:

Expected to create succesfully the resources

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy kubernetes in Ubuntu (bionic-beaver) with kubeadm. Follow the instructions for the deploy of kubernetes-nmstate for the arbitrary cluster. 

- Try to create any  NodeNetworkConfigurationPolicy resource.

- Check to see if the resource is created.

note: I have tried to create the resources with network-manager 1.10 and 1.20 but the result is the same.  Failing to create the resources.

**Comment by phoracek** [comment] 2020-02-10 17:17
Could you please share the following:

```
kubectl get nncp -o yaml
kubectl get nnce -o yaml
```

And logs of the running handlers?

**Comment by phoracek** [comment] 2020-02-10 17:17
Could you please share the following:

```
kubectl get nncp -o yaml
kubectl get nnce -o yaml
```

And logs of the running handlers?

**Comment by mardim91** [comment] 2020-02-11 08:21
@phoracek here

https://hastebin.com/ejafaqufuz.coffeescript

Here are the logs form the pod:

https://hastebin.com/sidafidati.cpp

**Comment by qinqon** [comment] 2020-02-11 10:20
@mardim91 something is fishy enactment state is progressing but policy is failed.

**Comment by mardim91** [comment] 2020-02-11 11:02
@qinqon here:

https://hastebin.com/wexizehipa.rb

**Comment by qinqon** [comment] 2020-02-11 12:23
Can you add the network manager logs to check why is not able to set the ip address ?

**Comment by mardim91** [comment] 2020-02-12 13:19
@phoracek @qinqon I think that this problem happened because I was writing wrongly the yamls. BTW network manager 1.20 is a hard limit for the system to work without a problem. People can actually download network manager 1.20 by adding this [1] to apt source for ubuntu. 

[1]:  deb http://cz.archive.ubuntu.com/ubuntu eoan main

I think we can close this issue

**Comment by qinqon** [comment] 2020-02-12 13:51
@mardim91 just before we close is the yaml syntax error appearing at kubectl get nnce -o yaml ?

**Comment by mardim91** [comment] 2020-02-12 14:35
@qinqon No it is not apparend in the logs what is the error. But I figured it out that the yaml is wrong. When I passed the correct yaml it worked.

**Comment by qinqon** [comment] 2020-02-12 16:53
The desiredState is validates by nmstate, the error should appear at enactments, can you share the failed config ?

**Comment by mardim91** [comment] 2020-02-12 16:58
So for instance I get this error now: https://hastebin.com/qugiwocage.cpp

When I am passing this config: https://hastebin.com/azabevugur.makefile 

I am trying to change the ip and the mtu with the above config but it never changes I do not know why. This is what i am currently facing

**Comment by phoracek** [comment] 2020-02-13 12:29
The log suggest the configuration is still in progress. Would you please apply the desired state and than wait for the result with:

```
kubectl wait nncp ens7-sec --for condition=Available --timeout 6m
```

If it fails to reach available, please share logs again and also:

```
kubectl get nnce -o yaml
```

**Comment by mardim91** [comment] 2020-02-13 13:45
@phoracek I have a hard time to find the correct yaml configuration to remove routes from the routing table? 

Do you know how I do that ? I am not seeing any example in the documentation

**Comment by phoracek** [comment] 2020-02-13 14:17
We don't test/support it in kubernetes-nmstate, haven't got to it yet (PRs are most welcome).

I looked into the nmstate API docs: https://github.com/nmstate/nmstate.github.io/blob/master/devel/api.md#route

> Remove specific route config entry:
> Just add Route.STATE: Route.STATE_ABSENT to the route entry to be removed.

I suspect you can add `"state": "absent"` to it, just the way it is with interfaces.

**Comment by mardim91** [comment] 2020-02-13 14:20
@phoracek Oh ok let me try that and I will let you know about the results :)

**Comment by mardim91** [comment] 2020-02-13 14:39
@phoracek it is working I created and removed a route succesfully :)

**Comment by phoracek** [comment] 2020-02-13 14:40
\o/ yeaaah!

**Comment by mardim91** [comment] 2020-02-13 16:06
@phoracek I am trying to run dns configurations and I get this error:  https://hastebin.com/ujalozusip.sql 

This is the configuration that I am passing:

https://hastebin.com/rajibelivu.makefile

Any idea ?

**Comment by phoracek** [comment] 2020-02-13 16:20
Seems like a bug in nmstate. Could I ask you to open a separate issue for it?

As a workaround, add following to the desired state:

```
interfaces: []
```

**Comment by mardim91** [comment] 2020-02-13 16:23
@phoracek 

That the workaround is not working now I get this error: 

https://hastebin.com/initugocal.sql

**Comment by phoracek** [comment] 2020-02-13 16:29
Is there any default route configured on the system? It looks like an nmstate bug. I will investigate more tomorrow, try to reproduce it and open on them.

If you get a chance to install https://github.com/nmstate/nmstate/ alone on your system and reproduce it via `nmstatectl`, that would make it faster to get resolved. We would be able to open a bug on them (or get advice on how to work around it).

**Comment by mardim91** [comment] 2020-02-14 07:55
@phoracek Hello I have already nmstate installed locally on my stystem so I guess I can give it a try no problem.

**Comment by phoracek** [comment] 2020-02-28 14:51
@mardim91 can we close this issue? Is the original problem resolved?

**Comment by mardim91** [comment] 2020-02-28 14:58
@phoracek Yes we can close this issue!

**Closed** 2020-02-28 15:15 UTC
