### ISSUE TITLE
Unable to create DNS configuration

### ISSUE THREAD

**Issue by mardim91** [nmstate/kubernetes-nmstate#416] opened 2020-02-13 16:26 UTC
**What happened**:

Tried to create some dns configuration throught this yaml:  https://hastebin.com/rajibelivu.makefile

But I got this error: https://hastebin.com/ujalozusip.sql

**Comment by phoracek** [comment] 2020-02-13 22:43
Policy:

```yaml
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: dns
spec:
  desiredState:
     dns-resolver:
        config:
          search:
          - example.com
          - example.org
          server:
          - 8.8.8.8 
```

Error:

```yaml
essage: |-
      error reconciling NodeNetworkConfigurationPolicy at desired state apply: , failed to execute nmstatectl set --no-commit --timeout 240: 'exit status 1' '' 'Traceback (most recent call last):
        File "/usr/bin/nmstatectl", line 11, in <module>
          load_entry_point('nmstate==0.2.1', 'console_scripts', 'nmstatectl')()
        File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 59, in main
          return args.func(args)
        File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 221, in apply
          return apply_state(statedata, args.verify, args.commit, args.timeout)
        File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 237, in apply_state
          checkpoint = libnmstate.apply(state, verify_change, commit, timeout)
        File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 60, in apply
          validator.validate_capabilities(desired_state, netinfo.capabilities())
        File "/usr/lib/python3.7/site-packages/libnmstate/validator.py", line 60, in validate_capabilities
          validate_interface_capabilities(state[Constants.INTERFACES], capabilities)
      KeyError: 'interfaces'
      '
    reason: FailedToConfigure
    status: "True"
    type: Failing
  - lastHearbeatTime: "2020-02-13T16:05:06Z"
    lastTransitionTime: "2020-02-13T16:05:06Z"
    reason: FailedToConfigure
    status: "False"
    type: Available
  - lastHearbeatTime: "2020-02-13T16:05:06Z"
    lastTransitionTime: "2020-02-13T16:05:06Z"
    reason: FailedToConfigure
    status: "False"
    type: Progressing
  - lastHearbeatTime: "2020-02-13T16:04:49Z"
    lastTransitionTime: "2020-02-13T16:04:49Z"
    message: All policy selectors are matching the node
    reason: AllSelectorsMatching
    status: "True"
    type: Matching
  desiredState:
    dns-resolver:
      config:
        search:
        - example.com
        - example.org
        server:
        - 8.8.8.8
```

**Comment by qinqon** [comment] 2020-02-14 08:45
Looks like you need to at a "interfaces" key to the desiredState.

**Comment by phoracek** [comment] 2020-02-14 08:47
That on its own would be a bug in nmstate. @mardim91 have tried it though but it failed on a different issue. We need to reproduce it with nmstatectl alone and open a bug on nmstate.

**Comment by mardim91** [comment] 2020-02-14 09:14
@phoracek @qinqon I have reproduced it with nmstatectl. It seems like a bug to me

Yaml: 

---
dns-resolver:
  config:
    search:
    - example.com
    - example.org
    server:
    - 8.8.8.8


Error:   

nmstatectl set native_dns.yaml 
Traceback (most recent call last):
  File "/usr/local/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==0.1.3', 'console_scripts', 'nmstatectl')()
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.1.3-py3.7.egg/nmstatectl/nmstatectl.py", line 59, in main
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.1.3-py3.7.egg/nmstatectl/nmstatectl.py", line 217, in apply
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.1.3-py3.7.egg/nmstatectl/nmstatectl.py", line 237, in apply_state
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.1.3-py3.7.egg/libnmstate/netapplier.py", line 60, in apply
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.1.3-py3.7.egg/libnmstate/validator.py", line 60, in validate_capabilities
KeyError: 'interfaces'

**Comment by phoracek** [comment] 2020-02-14 09:28
And if you add `interfaces: []` ?

**Comment by phoracek** [comment] 2020-02-14 09:29
Oh, please use nmstate 0.2.X, 0.1 is way too old and won't get fixes anyway. (Just trying to collect enough info to open a good issue on nmstate)

**Comment by mardim91** [comment] 2020-02-14 09:41
@phoracek Yes ok I just used the 1.3 because in kube-nmstate the image is 1.3 version.

**Comment by mardim91** [comment] 2020-02-14 09:51
@phoracek Same problem with v0.2.3

**Comment by phoracek** [comment] 2020-02-14 09:56
knmstate has 0.2 inside, https://github.com/nmstate/kubernetes-nmstate/blob/master/build/Dockerfile#L4

Then one last thing would be to show what happens with `interfaces: []` and then we can open a bug!

**Comment by mardim91** [comment] 2020-02-14 09:58
@phoracek Yes but when I followed the instruction to deploy the nstate operator it downloaded the 1.3 image.

**Comment by phoracek** [comment] 2020-02-14 09:59
Gotcha. The new operator version should be out today/tomorrow.

**Comment by mardim91** [comment] 2020-02-14 10:00
the Yaml 👍 
---
dns-resolver:
  config:
    search:
    - example.com
    - example.org
    server:
    - 8.8.8.8
interfaces: []

nmstate version -> v0.2.3
the Error:

nmstatectl set native_dns.yaml 
Traceback (most recent call last):
  File "/usr/local/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==0.2.3', 'console_scripts', 'nmstatectl')()
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/nmstatectl/nmstatectl.py", line 59, in main
    return args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/nmstatectl/nmstatectl.py", line 217, in apply
    statedata, args.verify, args.commit, args.timeout
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/nmstatectl/nmstatectl.py", line 241, in apply_state
    rollback_timeout=timeout,
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/nm/nmclient.py", line 98, in wrapped
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/netapplier.py", line 67, in apply
    state.State(desired_state), verify_change, commit, rollback_timeout
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/netapplier.py", line 128, in _apply_ifaces_state
    metadata.generate_ifaces_metadata(desired_state, current_state)
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/metadata.py", line 74, in generate_ifaces_metadata
    _generate_dns_metadata(desired_state, current_state)
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/metadata.py", line 260, in _generate_dns_metadata
    searches,
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/metadata.py", line 280, in _save_dns_metadata
    "name servers: %s" % server
libnmstate.error.NmstateValueError: Failed to find suitable interface for saving DNS name servers: 8.8.8.8

**Comment by phoracek** [comment] 2020-02-14 10:04
Now one last step from our side, could you please open an issue describing this (with both `interfaces` and without it) to https://github.com/nmstate/nmstate/issues?

**Comment by mardim91** [comment] 2020-02-14 10:05
@phoracek Yes I will do it in a minute

**Comment by mardim91** [comment] 2020-02-14 10:19
Done https://github.com/nmstate/nmstate/issues/791

**Comment by qinqon** [comment] 2021-07-14 10:41
Fixed with https://github.com/nmstate/nmstate/pull/828

**Closed by qinqon** 2021-07-14 10:41 UTC
