### ISSUE TITLE
Uninstall Leaves CRDs Behind

### ISSUE THREAD

**Issue by anandgiddani** [nmstate/kubernetes-nmstate#1166] opened 2023-04-04 17:37 UTC
**What happened**: While I am trying to uninstall/delete the nmstate from K8s cluster, CRDs are not removing. 

**What you expected to happen**: While installing NMState CR it is creating CRDs and while uninstalling the CR it should delete those CRDs.

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**: 

**Environment**: K8s Cluster 

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):  quay.io/nmstate/kubernetes-nmstate-handler:v0.74.0
- NetworkManager version (use `nmcli --version`): nmcli tool, version 1.10.6
- Kubernetes version (use `kubectl version`): 
- OS (e.g. from /etc/os-release): ubuntu 18.04.6
- Others: I know I am not using the required NetworkManager version here but as per my knowledge it may not causing this CRDs deletion issue.

**Comment by qinqon** [comment] 2023-04-05 09:00
CRDs are not removed by design

**Comment by anandgiddani** [comment] 2023-04-05 09:37
so we need to remove those manually after deleting/uninstall the nmstate?

**Comment by qinqon** [comment] 2023-04-05 11:28
@cybertron do you remember why was like that ? I think it was realted to upgrade so users don't get their NNCPs removed, although I don't know why create/delete/create of NMstate has to be done at upgrades.

**Comment by cybertron** [comment] 2023-04-17 21:36
I do not remember. All of that is managed by OLM so if that's the behavior it would be on their side.

Although maybe it had something to do with the migration from CNV to standalone? I thought in that case they were installed side-by-side, but I guess if you uninstalled and then reinstalled it might be a problem? Or maybe when you uninstalled the old one it would remove the CRDs for both?

**Comment by qinqon** [comment] 2023-06-05 11:37
Closing since this is by design

**Closed by qinqon** 2023-06-05 11:37 UTC
